### PR TITLE
Typo: DbIpLocarionAndIspLineReader 

### PR DESCRIPTION
**Pull request by jgolatkar**
class name changed : DbIpLocationAndIspLineReader
updated class references to new class name

### CODE REVIEW

**Comment by jgolatkar** [comment]
@stykiaz looks like there is issue on Travis CI build

The command "openssl aes-256-cbc -K $encrypted_9dd2761de049_key -iv $encrypted_9dd2761de049_iv -in travis.gpg.pem.enc -out travis.gpg.pem -d" failed and exited with 1 during

**Comment by nenko-tabakov** [comment]
@jgolatkar Can you please merge the latest changes from master as they should fix this issue

**Comment by jgolatkar** [comment]
@nenko-tabakov i have merged master

**Comment by nenko-tabakov** [comment]
Great, thanks 😄

**Pull request merged**
